version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
    - "27017:27017"
    volumes:
    - ./data/mongodb:/opt/mongodb
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_PASSWORD=password
    volumes:
    - ./data/rabbitmq:/bitnami/rabbitmq
